services:
  arka-app:
    build: ${PWD}/ARKA-APP/server
    container_name: arka-app
    environment:
      PYTHONUNBUFFERED: "1"
      ROUTING_URL: http://arka-routing:8087
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER:-arka}:${POSTGRES_PASSWORD:-arka}@postgres:5432/${POSTGRES_DB:-arka}
      ORCH_API_KEY: ${ORCH_API_KEY:-}
      CATALOG_SOURCE: ${CATALOG_SOURCE:-db}
      AGENTS_SOURCE: ${AGENTS_SOURCE:-db}
      ROUTING_SOURCE: ${ROUTING_SOURCE:-db}
      SESSIONS_SOURCE: ${SESSIONS_SOURCE:-auto}
      ARKA_OS_ROOT: /app/ARKA_OS
    volumes:
      - ${PWD}/ARKA-APP/server:/app:rw
      - ${PWD}/ARKA_OS:/app/ARKA_OS:ro
      - ${PWD}/ARKA_META:/app/ARKA_META
    command: ["uvicorn", "main:APP", "--host", "0.0.0.0", "--port", "8080"]
    ports:
      - "${ARKA_APP_PORT:-8080}:8080"
    depends_on:
      arka-routing:
        condition: service_healthy
      postgres:
        condition: service_healthy

  arka-web:
    image: node:20-alpine
    container_name: arka-web
    working_dir: /app
    volumes:
      - ${PWD}/ARKA-APP/web:/app
    environment:
      - HOST=0.0.0.0
      - PORT=5173
      - REACT_APP_BACKEND_URL=http://arka-app:8080/api
      - CHOKIDAR_USEPOLLING=true
    command: ["sh","-lc","npm install && npm start"]
    ports:
      - "5173:5173"
    depends_on:
      arka-app:
        condition: service_started
