version: "3.9"
services:
  adapter-codex:
    build:
      context: ${PWD}
      dockerfile: ARKA-DOCKER/docker/adapter-codex/Dockerfile
    container_name: adapter-codex
    environment:
      PYTHONUNBUFFERED: "1"
      ADAPTER_NAME: codex
      API_BASE: ${CODEX_API_BASE:-https://api.openai.com/v1}   # exemple compatible OpenAI
      API_KEY: ${CODEX_API_KEY:-}
      TIMEOUT_SEC: ${CODEX_TIMEOUT_SEC:-60}
      FAULT_INJECTION: ${CODEX_FAULT_INJECTION:-none}           # none|timeout|http500
      AUTH_MODE: ${CODEX_AUTH_MODE:-auto}
      CLI_CMD: ${CODEX_CLI_CMD:-ollama}
      CLI_CHAT_ARGS_TEMPLATE: ${CODEX_CLI_CHAT_ARGS_TEMPLATE:-run {model}}
      CLI_TIMEOUT_SEC: ${CODEX_CLI_TIMEOUT_SEC:-120}
    ports:
      - "9093:9093"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9093/healthz"]
      interval: 5s
      timeout: 3s
      retries: 60

  adapter-openai:
    build:
      context: ${PWD}
      dockerfile: ARKA-DOCKER/docker/adapter-openai/Dockerfile
    container_name: adapter-openai
    environment:
      PYTHONUNBUFFERED: "1"
      ADAPTER_NAME: openai
      API_BASE: ${OPENAI_API_BASE:-https://api.openai.com/v1}
      API_KEY: ${OPENAI_API_KEY:-}
      TIMEOUT_SEC: ${OPENAI_TIMEOUT_SEC:-60}
      FAULT_INJECTION: ${OPENAI_FAULT_INJECTION:-none}          # none|timeout|http500
      AUTH_MODE: ${OPENAI_AUTH_MODE:-auto}
      CLI_CMD: ${OPENAI_CLI_CMD:-ollama}
      CLI_CHAT_ARGS_TEMPLATE: ${OPENAI_CLI_CHAT_ARGS_TEMPLATE:-run {model}}
      CLI_TIMEOUT_SEC: ${OPENAI_CLI_TIMEOUT_SEC:-120}
    ports:
      - "9094:9093"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9093/healthz"]
      interval: 5s
      timeout: 3s
      retries: 60
